[package]
name = "jeopardy"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "*", features = ["full"] }
anyhow = "*"
thiserror = "*"
async-trait = "*"
# mockall = "*"

# json
serde = { version = "*", features = ["derive", "rc"] }
serde_json = "*"

# web server
axum = { version = "*", features = ["ws"] }
futures-util = "*"
tower-http = { version = "*", features = ["fs"] }
bytes = "*" # used internally by axum

# logging
tracing = "*"
tracing-subscriber = "*"

[features]
# login-timeout-test = []